spring.cloud.gcp.trace.enabled=true
management.tracing.sampling.probability=1.0
spring.application.name=java-evaluator
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
